# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-01 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djuser',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='djuser',
            name='doj',
            field=models.DateField(blank=True, null=True),
        ),
    ]
